# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48e93fc516baa1cb4c2ac2fe6c6e497cc58a6ba8e9a05bc2c0a8eb4c535bd3cc04e197cecc584293c39470f872e0e9ea18083a29a6688adada125a77f179c56

test:
  secret_key_base: e549fe3fef63c160bf804242d769047e9c31a7dc336a94cfdc45dccaf82dd3b452239b9ffcccb9808b276d60543aeaa69d6fec96a0476672601f0b61711ca07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
